### ISSUE TITLE
Recol·locar els elements a la pàgina

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#101]
Dividint #5:
Ara mateix els elements de la pàgina (formulari de cerca, vídeo, text, botó per penjar vídeo...) estàn col·locats sense cap critèri.
Caldria decidir com organitzar-los de manera que sigui el més pràctic possible.

Si algú té una proposta, seria genial acompanyar-la d'una imatge/esquema (ja sigui feta a mà, en paint o com sigui)

**Comment by lauramasclans** [comment]
Dividir la pantalla en tres columnes de proporció aproximada: 30-60-30.
En la primera que hi hagi l'opció de navegar alfabèticament.
En la segona hi trobarem el logo i la paraula Signepèdia com a títol. A sota la casella de "Escriu una paraula". A sota el botó de "Tradueix". A sota el vídeo. A sota en petit l'autor. A sota en lletra mitjana "Potser també t'interessa.." o d'altres missatges similars.
En la tercera columna hi trobem el nombre d'entrades registrades "Ja tenim 2598 entrades!". A sota el botó "Afegir un signe". A sota un apartat amb "Els signes més vists". A sota un apartat amb "la teva Signepèdia" on estiguin disponibles els vídeos que has buscat recentment.
A sota de les tres columnes faria una fila estreta i petita on hi hagués informació de l'estil: Aquest servei està basat en el programari lliure GitHub/Masclins/signepedia. Avís legal. Política de privacitat. Última actualització.

**Comment by Masclins** [comment]
Amb l'@Atlantidattt hem fet la primera prova de com podria quedar.
A veure què us sembla (està a la carpeta `proves/` de la branca `html`)
![exemple](https://user-images.githubusercontent.com/7271634/39886762-bab9b5de-5490-11e8-906a-a97565f2bfb3.jpg)

**Comment by lauramasclans** [comment]
jajajja genial! amb dues columnes crec que pot quedar bé! potser si que
posaria alguna petita linia fina dividint les columnes.

No he pogut treballar-hi aquesta setmana! però ara que menvaig a berlin
m'emportaré l'ipad i a l'avió i estones mortes aniré fent  diferents
dissenys per al logo!


2018-05-12 19:24 GMT+02:00 Masclins <notifications@github.com>:

**Comment by Masclins** [comment]
He estat mirant últimament una opció amb tres columnes que també m'agrada. Divendres la discuteixo amb l'Eli.
