### ISSUE TITLE
Dissenyar el text de la pàgina

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#102]
Dividint #5:

Ara mateix la tipologia, color, mida, etc. del text que surt a la pàgina està posat sense gaire criteri i simplement per tenir algun exemple.
Caldria decidir aquests aspectes, i veure per a cada missatge o fragment de text el format més adeqüat.

Tanmateix, el text en sí també està posat per donar una idea del que podem dir.
Caldria decidir quines paraules expresen millor el que es vol transmetre i a més mantenen el to que volem per la pàgina.

**Comment by Mireiatt** [comment]
Tot allò referent a tipus de lletra, tamanys i com s'organitza és veritablement complicat d'explicar i té força ciència. Si no funciona a la primera o funciona de forma discreta, caldrà plantejar-se un redisseny en el futur i no us ho aconsello.

Per això us proposo que hi feu un cop d'ull a aquest link, que parla de la Wikipèdia i les seves noves fonts. Aprofitar-nos de l'experiència d'altres ens estalviarà problemes.

https://omicrono.elespanol.com/2014/04/wikipedia-cambia-de-aspecto-con-una-nueva-tipografia/
