### ISSUE TITLE
Comptar el nombre de registres del diccionari

### ISSUE THREAD

**Issue by Atlantidattt** [Masclins/signepedia#116]
Actualment s'ha d'introduir manualment al frontend el nombre de registres totals que hi ha al diccionari.
Per tal de donar una bona resposta a #101 cal que es faci un recompte automàtic i surti publicat en el frontend.

**Comment by Masclins** [comment]
Quan cerquem sinònims també surten alternatives, igual que amb alguns registres.
Potser seria més interessant dir quants vídeos diferents tenim registrats.

**Comment by Masclins** [comment]
Aturo aquesta Issue fins que estigui la Base de Dades implementada, ja que altrament requeriria fer una feina totalment inútil.

**Comment by Masclins** [comment]
Tancada, ja que està solucionada a la branca `MySQL`
