### ISSUE TITLE
Incloure comentaris a les entrades

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#122]
Per algunes paraules tenim diverses alternatives. Sovint es deu a que hi ha matisos pels que es fan servir diferents signes.
En molts casos ho hem pogut explicar amb la mateixa paraula. Ara bé, és probable que no siempre puguem fer-ho així.
Caldria afegir el camp de comentaris a les entrades del diccionari i mostrar-les al frontend.

**Comment by Atlantidattt** [comment]
Ara mateix no tenim els coneixements teòrics per fer-ho però quan altres persones comencin a col·laborar estaria bé que tinguessin aquesta opció per fer una signepèdia tant clara i rica com la mateixa LSC.

**Comment by Mireiatt** [comment]
Què us semblaria categoritzar les paraules, segons tenen només un signe o més d'un? D'aquesta forma inclús es facilita la col·laboració d'altres persones en penjar vídeos, perquè està clar que les paraules que es poden signar de més d'una manera necessiten, a priori, més ajuda.

**Comment by Masclins** [comment]
Què fer en els casos aquest és un tema que requereix força atenció.
De moment ho hem "solucionat" proposant l'opció `(2)`, però caldria pensar una millor alternativa.
Tanmateix, caldrà decidir com mostrar aquests casos a la web.

Potser una sol·lució seria simplement fer vídeos on sortíssin les diferents opcions...? (quan el cas és com *car* que no hi ha cap diferència de significat entre els tres possibles signes).

**Comment by Atlantidattt** [comment]
_Per algunes paraules tenim diverses alternatives. Sovint es deu a que hi ha matisos pels que es fan servir diferents signes._ En aquest casos s'ha de poder navegar entre les diferents opcions (per exemple: mitjançant fletxes). Per defecte hauria de sortir el millor valorat per l'usuari.

_Caldria discutir si val la pena afegir un apartat de comentaris a les entrades, que faríem servir només quan sigui necessari._ Crec que sí que hauria d'existir per explicar les diferencies respecte als altres vídeos de l'entrada (per exemple: intensitat, estat d'ànim, zona d'ús, etc.)

**Comment by Masclins** [comment]
Editat per representar-ho.

**Comment by Masclins** [comment]
Resolt a la branca `remodel`

**Comment by Masclins** [comment]
Resolved by #171 on develop
