### ISSUE TITLE
Crear Base de Dades

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#128]
Segons anem volent afegir funcionalitats, es fa necessària una Base de Dades.

De les issues actuals, n'hi ha diverses que serien molt més fàcils si tinguéssim una BD:
- #60 
- #113 
- #117 
- #118 (especialment si tenim usuaris)
- #123 
- #126
- Creació d'usuaris, que serà desitjable, a futur.
- Anàlisi d'usuaris i el seu comportament.

A més, desmarcaria l'evolució del projecte de la de la base de dades. I aquest em sembla el punt més important. El producte que estem desenvolupant és un diccionari **col·laboratiu**. El producte pot estar acabat independentment del seu contingut, ja que el producte el que ha de fer és permetre que el contingut creixi. Tal i com ho plantejem ara, tenint el `diccionari.csv` dins el projecte, va estretament relacionat el producte amb la creació de contingut.

**Comment by Masclins** [comment]
https://www.pickaweb.co.uk/kb/how-do-i-create-a-mysql-database-on-a-vps/
Aquestes instruccions semblen prou simples de seguir per a crear-la.
Ara bé, no tinc clar com accedir-hi des de fora el servidor...

**Comment by Mireiatt** [comment]
No voldria ser una aixafa-guitarres, però la creació de tota base de dades necessàriament afectarà a l'apartat legal del projecte.

**Comment by Masclins** [comment]
Crear una base de dades **no** afecta a l'apartat legal.
El que l'afectarà és **què** li posem.
Lògicament, si permetem registrar usuaris, caldrà adaptar la política de privacitat.
Si fem servir la base de dades per guardar informació de què cerquen els usuaris, dependrà de si guardem **qui** ha fet la cerca (ja sigui amb codi d'usuari o IP). De totes maneres, en aquest cas, tampoc estaria de més actualitzar la política de privacitat, tenint-la llesta per quan tinguem usuaris registrats (si és que fem primer això que registrar usuaris).
