### ISSUE TITLE
Configurar servidor

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#14]
Per fer la web accessible des d'arreu, cal preparar un servidor amb aquest objectiu.

Caldrà:
- Aconseguir un servidor (ordinador vell?)
- Aconseguir un domini (?)
- Modificar el codi perque faci servir el servidor remot
- Afegir una opció per poder fer servir un servidor local, pel desenvolupament

**Comment by BrunoBA91** [comment]
Van algunes idees:
- Servidor i/o servidor local: podriem fer servir una Raspberry PI per a muntar el servidor. Opció barata i força eficient al menys al principi del projecte.
- Com a suport pel servidor podriem fer servir Apache. --> https://httpd.apache.org/

Un tutorial de com fer-ho tot seria algun com aquest --> https://www.prometec.net/raspberry-pi-servidor/#

**Comment by Masclins** [comment]
Sembla que tenim una opció interessant i barata (mig recomenada pel @kenan-rhoton): https://www.ovh.com/world/vps/vps-ssd.xml
Serien 3,35€/mes si paguem anualment.
