### ISSUE TITLE
Guardar en el servidor els vídeos enviats

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#143]
Ara mateix quan s'envia un vídeo, la informació i el vídeo s'envien per email. Això implica que la pujada al servidor haurà de ser manual forçosament.

L'alternativa seria que aquesta informació es guardés directament al servidor per poder resoldre #126 

Això requerirà una revisió de les Condicions d'ús i Política de Privacitat.

**Comment by Masclins** [comment]
He estat investigant i semblaria que això pot suposar un problema de vulnerabilitat.
Caldria estudiar bé aquesta part.

També caldrà decidir com ho gestionem per evitar que els videos acabin menjant-se massa memoria del servidor. Idees (que probablement calgui combinar):
- Limitar la mida del vídeo enviat
- Limitar el número de vídeos guardats
- Avisar (per correu?) a un *admin* quan hi hagi nous vídeos perque no se n'acumuli masses

**Comment by Atlantidattt** [comment]
Quan el vídeo pesa massa, avisaria a l'usuari del problema i li diria que farem el possible per penjar-lo però que no li ho podem garantir.
Quan s'arribi al màxim de vídeos permesos en el servidor, si es continuen enviant vídeos però no hi caben, els enviaria directament al e-mail de la signepèdia.
Enviaria un avís a l'admin quan s'hagués arribat més o menys a la meitat de vídeos permesos en el servidor i un altre quan estigui ple.

**Comment by Masclins** [comment]
Tanco aquesta issue.
Per #150, farem servir YouTube per guardar-hi els vídeos.
