### ISSUE TITLE
Agilitzar les consultes a la Base de Dades

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#147]
Hi ha dos àmbits importants a considerar per poder accelerar els temps de consulta:
- **Registre sincrònic**
Ara mateix la cerca no es du a terme fins que s'ha registrat la paraula cercada. Això realment no té cap sentit: Podem retornar el resultat de la cerca independentment de si ja hem registrat la cerca o no.
- **Accés remot a la base de dades**
Pels tests o el desenvolupament, caldrà connectar-se remotament a la base de dades. Ara bé, el servidor no hauria d'haver-ho de fer remotament. El problema ve de que al estar-se executant el backend dins el Docker, no podem simplement connectar-nos al `localhost`.

**Comment by kenan-rhoton** [comment]
El segon cas està bé: sempre has de considerar que la base de dades està "en remot" (encara que acabi estant a la mateixa màquina)

El primer cas es tema de operacions asíncrones, tot i que em sorprendria moooolt que afectés gaire al rendiment.

Perquè cal agilitzar les consultes? Quant triguen?

**Comment by Masclins** [comment]
Fent servir la base de dades de test (que té menys entrades, però això no hauria d'importar):
- Si la tenim registrada i no té sinònims: Menys d'1 segon.
- Si té sinònims: 3-4 segons.
- Si no té sinònims (i.e. sospitem que està mal escrita): Pot ser més de 5 segons.

Això ho he comprovat fent servir `new Date()` i `getTime()` de javascript.
Potser el problema té més a veure amb les APIs externes... Casum!

PD: Perquè *sempre* he de considerar que la base de dades està "en remot"?

**Comment by kenan-rhoton** [comment]
Sembla molt lent, si, miraré si hi ha algún problema d'eficiència en les cerques actuals.

I sempre hem de considerar que estigui en remot perque així no ens limitem i la podem tenir on vulguem si posteriorment ho volem canviar sense problemes.
