### ISSUE TITLE
Pujar videos a un canal de youtube dedicat

### ISSUE THREAD

**Issue by obs-86** [Masclins/signepedia#150]
Actualment hi ha videos que formen part del repositori... Versionar arxius binaris és un pecat!!!
A més de tenir moltes implicacions negatives a llarg termini a nivell de manteniment, escalabilitat...

Proposta:
1. Fer que el frontend pugi els videos nous (carregats pels usuaris) en un canal privat dedicat de la signepedia
2. Validació manual del nou video per part d'algun membre autoritzat de la signepedia 
(video OK -> es fa public i s'afegeix a la base de dades, video NOK -> s'elimina)

Això permetria desempallegar-nos del gran volum de dades que requereixen i estalviar problemes de "hosting" i conversió de formats de video entre d'altres.

https://developers.google.com/youtube/v3/quickstart/nodejs

**Comment by Masclins** [comment]
Ho hem parlat cuatre colaboradors del projecte i optarem per aquesta vía.
Deixo aquesta issue dedicada a pujar els vídeos a YouTube.
