### ISSUE TITLE
Canviar taula views

### ISSUE THREAD

**Issue by Atlantidattt** [Masclins/signepedia#164]
Actualment la taula de views distingeix entre majúscules i minúscules. Guarda la paraula i el número.
Ho hauria de guardar sempre en minúscules per evitar repeticions i hauria de tenir l'opció ignorar per poder suprimir cerques sense sentit com per exemple: asdhasòh.

**Comment by Masclins** [comment]
Canviat a #167

**Comment by Masclins** [comment]
Resolved by #171 on develop
