### ISSUE TITLE
Guardar cerques del diccionari

### ISSUE THREAD

**Issue by Atlantidattt** [Masclins/signepedia#165]
Actualment en el diccionari no es registra el número de cerques de cada paraula.
Quan es fa una cerca i tenim la paraula registrada i validada s'hauria d'anotar en el diccionari per tal de saber quines entrades són les més visitades.

**Comment by Masclins** [comment]
Això tindria sentit un cop haguem implementat #117.
Sobretot pensant en que la cerca dels vídeos més visitats sigui més ràpida.
