### ISSUE TITLE
Mostrar dos (o més) símbols per una mateixa paraula

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#18]
Sabem que hi ha paraules que tenen dos o més símbols en LSC.

Hem de decidir què fer en aquests casos i adaptar el codi perquè actui en conseqüència.

**Comment by BrunoBA91** [comment]
Tema important d'abordar. Implica que hem de pensar en com programar-ho des del dia 1 ja que si començem a programar per a símbols individuals i després passem a paraules amb més d'1 símbol el codi seria molt diferent.

Una primera proposta seria un algoritme basat en classes. S'hauria de fer un treball previ de com dividir els tipus de signes; d'aquesta manera a l'hora de fer servir més d'un, és més fàcil fer un "match" entre les possibles combinacions.

**Comment by Masclins** [comment]
Veig viable fer-ho tot desde una única entrada. En el csv (que en el futur, si cal, serà Base de Dades) pot haver-hi els camps `"url", "url2", "url3", "url4", "url5"`. Quan troba la paraula passa tantes urls com camps trobi amb algún valor.

Vaja, que no hauria de ser un problema pel backend passar aquesta info. Em preocupa més com ho mostrem al frontend. No tant perque sigui difícil com perque quedi bé.

**Comment by Masclins** [comment]
Estic començant a pensar que potser no és viable tenir "múltiples camps".
Estic pensant en tenir dos diccionaris.

1. Un on hi ha totes les entrades, fins i tot repetides (però amb noms diferents, tipus `"paraula 1", "paraula 2"`.
2. Un altre que fa de pont. Per cada paraula, té un array amb les entrades que corresponen a aquella paraula.

Així, quan busquéssim una paraula, consultariem el diccionari 2. Aquest ens donaria un array que convertiriem (fent consultes al diccionari 1) en un array d'entrades. A partir d'aquí, segons correspongui, decidirien què mostrar.

**Comment by BrunoBA91** [comment]
Ostres m'agrada força la idea. No sé si és gaire òptim però sí que és funcional. Tirem endavant amb aquesta idea.

**Comment by Masclins** [comment]
Estem avançant molt amb #27 i #31 (gràcies @Atlantidattt) però encara no hem decidit aquest punt.
Ho dic perque aquest punt pot marcar molt com han de ser les entrades, i per tant pot ser que la feina de #31 hagi de ser d'una manera o una altra.

Proposta 1 (amb l'exemple de **rosa**)
1. L'usuari cerca "rosa".
2. Rep el missatge: `Cerca "rosa (flor)" o "rosa (color)" segons el significat que vulguis.`
3. L'usuari cerca "rosa (flor").
4. Es mostra el vídeo corresponent.

*En un futur, `rosa (flor)` i `rosa (color)` podrien ser clicats i cercats automàticament.*

Proposta 2 (amb l'exemple de **rosa**)
1. L'úsuari cerca "rosa".
2. Es mostren dos vídeos: Un sota un encapcelament *Flor* i un altre, *Color*.

*Aquesta opció pot ser problemàtica quan hi hagin moltes accepcions.*

**Comment by Atlantidattt** [comment]
M'agrada molt la proposta 1.

**Comment by Masclins** [comment]
La lògica que seguirà el backend seria la següent:

1. Cerco la primera entrada de la paraula preguntada.
2. Miro si té una "Nota".
3. Si la té, entenc que hi ha altres accepcions.
4. Busco totes les entrades per la paraula cercada.
5. Proposaré les entrades posant entre parèntesis el que hi diu a la "Nota".

Per a que això funcioni, amb el cas de rosa, al diccionari hauriem de tenir:
```csv
"rosa","flor","","",""
"rosa","color","","",""
"rosa (flor)","","http://...","youtube","generalitat"
"rosa (color)","","videos/rosa(color).mp4","","Tània"
```

Requereix una mica de feina. En aquest exemple he fet que la columna `"nota"` estigui al principi: Crec que ho faria més fàcil de llegir.

Què us sembla? Anem per aquesta línea?

**Comment by Masclins** [comment]
Tanco aquesta Issue per reobrir-ne una explicant ben bé com ho hauriem de solucionar.
