### ISSUE TITLE
Identificar el vocabulari que falta

### ISSUE THREAD

**Issue by Atlantidattt** [Masclins/signepedia#43]
Per tal de fer millor #31 i facilitar la col·laboració amb altres persones que coneixen la LSC, no tenim cap referència de les paraules que manquen gravar.
Hauriem de creuar les paraules que tenim actualment en el `diccionari.csv` amb les d'un diccionari català obert com la Viquipèdia o https://github.com/softcatala per tal de crear un llistat del lèxic que resta per gravar.

**Comment by Masclins** [comment]
Em sembla **molt** bona idea i important.
Seria ideal crear un script que generi un document amb aquesta informació i editaré `CONTRIBUTING.md` per explicar-ho.

Realment és probable que Softcatalà tingui alguna API amb un diccionari. La Viquipèdia també pot donar-nos una referència d'entrades que seria interessant traduïr (a més, potser podem obtenir el número de visites de cadascuna, que poden ser una referència de com d'important seria incloure-les al diccionari).

**Comment by Masclins** [comment]
La Wikipedia ofereix una llista de les 8000 paraules més freqüents a la Viquipèdia: https://en.m.wiktionary.org/wiki/Wiktionary:Frequency_lists/Catalan
