### ISSUE TITLE
Pujar vídeos des del frontend

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#47]
Actualment el procediment per pujar vídeos (explicat a `docs/CONTRIBUTING.md`) és força complicat per algú que només vulgui col·laborar gravant vídeos.

Caldria habilitar el frontend perque des de la mateixa web sigui possible pujar vídeos.

Per fer-ho, haurem de decidir algunes coses:
* Com ha de mostrar-se la funcionalitat al frontend (com es veu a la web la opció per pujar un vídeo)
* Quina informació demanem (paraula, usuari, nota...?)
* Què fem si el vídeo ja existeix (impedim en el mateix moment la pujada? Avisem a l'usuari?...)
* Com revisem el vídeo? (És important que es pugui fer des del frontend fent servir una mena d'usuari administrador? Actualitzem el repositori des del servidor?...)

**Comment by Atlantidattt** [comment]
1. Pel que fa a la funcionalitat del frontend:
   - Faria  un botó amb el missatge "afegir un signe" i que al clicar-lo s'obrís una nova pestanya.
   - A la nova pestanya hi posaria el títol "Col·labora amb el projecte signepèdia"
   - Sota el títol escriuria el cos "Signepèdia és un projecte lingüístic col·laboratiu que vol facilitar l'accés a la LSC a tota la població. Aquest projecte, igual que qualsevol llengua, evoluciona i creix, amb la teva col·laboració ho farem millor!"
   - Sota el cos afegiria un formulari amb:
**Autor** _aquest és el nom que sortirà com a autor del vídeo_
**Correu electrònic** _per donar-te feedback_
**Com penjar un vídeo** _ex: bona llum, enfocament, fons llis, roba llisa i fosca, sense àudio..._
**Paraula** _aquesta és la paraula de referència, estigues atent als errors ortogràfics_
**Comentaris** _ex: hi ha més signes per aquesta paraula? aquest signe significa quelcom més?_
**Penja el vídeo** i que puguis seleccionar-ne amb un selector d'arxius.
Adjunto tres imatges de referència perquè facin d'exemple:
![col laboracio](https://user-images.githubusercontent.com/38889941/39544991-12cdec96-4e50-11e8-966b-df399d353894.png)
D'aquest m'agrada el botó "no sóc un robot", en tindrem un?
![col laboracio amic](https://user-images.githubusercontent.com/38889941/39544993-12edb9ea-4e50-11e8-94fd-c0bb7075c4fe.png)
D'aquest m'agrada l'enllaç d'enviar-ho a un amic. És possible fer-ho?
![col laboracio politica privacitat](https://user-images.githubusercontent.com/38889941/39544994-130b9fa0-4e50-11e8-8f5c-e7b7577c9b72.png)
En aquest hi ha afegida la política de privacitat i l'avís legal, nosaltres en tindrem?

**Comment by Masclins** [comment]
Moltes gràcies i molt bona investigació.
La idea que tinc és intentar que cada Issue representi un únic problema, i fer el mínim necessàri per solucionar-lo degudament. Si intentem solucionar múltiples problemes (o problemes derivats) alhora, serà molt difícil avançar i fer que tot vagi encaixant.

Per tant, de cara a la primera pregunta (*Com ha de mostrar-se la funcionalitat al frontend?*), amb el que es dit em quedaria amb el següent:
* Afegim un botó que obri una altra pàgina (en una pestanya diferent, o no)
* En aquest botó es presenta el formulari per penjar el video (em semblen molt bé els camps plantejats)
* Avís legal/política de privacitat (aquesta part és molt important, ja que si no podriem tenir problemes per penjar els vídeos a la xarxa)

Caldria anotar a les instruccions (i potser afegir una casella amb aquest fí) que la persona gravada ha de ser major d'edat.

*No sóc un robot* caldrà, en algún moment, però ara per ara no ho afegiria: dubto molt que tinguem cap problema amb això, com a mínim ara al principi. *Envia a un amic* em sembla una mica estrany: Què li enviaries?

Ara quedaria contestar: *Com revisem el vídeo?*

**Comment by Masclins** [comment]
Per ara l'únic registre d'usuaris que tindrem serà pels col·laboradors de GitHub, ja que GitHub mateix gestiona les comptes.

Tant com sigui possible, evitarem tenir usuaris registrats de cap manera, ja que això implicaria tenir una base de dades d'usuaris, que comporta certa difícultat: Si no és necessàri, ho evitaria.

Crec que l'ideal seria:
1. El video es guarda al servidor, amb la informació pertinent.
2. Cada cert temps, al/s col·laboradors de GitHub que s'hagin assignat a la tasca de revisió, els envio un paquet de vídeos per revisar.
3. Un col·laborador es responsabilitza d'un paquet de vídeos, i els revisa.
4. El revisor, fa el commit al repositori amb els vídeos que afegirem i envia un mail (predefinit) explicant què hem fet amb els videos que ens han enviat els usuaris.
