### ISSUE TITLE
Dissenyar l'estètica de la web

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#5]
En algún punt caldrà fer que la web d'accés sigui agradable i fàcil d'utilitzar.

Podem aprofitar aquest mateix *issue* per discutir com hauria de ser.

**Comment by Masclins** [comment]
Després de #46, tot el necessàri per canviar l'estil del que ja existeix a la web es troba a `frontend/public/css/style.css`. Si algú s'animés: https://www.w3schools.com/css/

Per moure els elements de lloc, afegir-ne, canviar-ne, etc. cal tocar `frontend/views/index.ejs`. Excepte per les parts entre `<% %>` la resta és HTML. Si algú s'animés: https://www.w3schools.com/html/

**Comment by Mireiatt** [comment]
Jo em puc encarregar de les qüestions estilístiques si voleu.

**Comment by Masclins** [comment]
I tant! La idea és precisament aquesta, que tothom col·labori aportant el que sàpiga i li vingui de gust.

Tot i que l'app ja es pot fer servir seguint les instruccions al `README.md` he d'admetre que no és fàcil. Per ara crec que seria molt més interessant que, @Mireiatt, centréssis esforços en dissenyar el logo (#42) i quan es pugui accedir a la web remotament te la mires per proposar-ne millores.

**Comment by Masclins** [comment]
Divideixo aquesta Issue en altres, que serveixin per poder anar-hi treballant millor.
El projecte *Disseny de la Signepèdia* hauria de recollir aquestes issues.

**Comment by Masclins** [comment]
He tancat totes les issues que vaig obrir perque ho enfocarem diferent amb l'ajut de l'Eli.
