### ISSUE TITLE
Bug: frontend no accepta "?"

### ISSUE THREAD

**Issue by Atlantidattt** [Masclins/signepedia#59]
Quan cerco al frontend "com estàs?" em busca "com estàs" i l'interrogant desapareix.
Hauria de buscar l'expressió amb l'interrogant.
![com estas](https://user-images.githubusercontent.com/38889941/39589619-08c75124-4eff-11e8-91ab-a0678f89011c.jpg)

**Comment by Masclins** [comment]
Per cercar les paraules fem servir REST requests.
Em temo que les REST requests interpreten `?` com a codi especial.
Podem fer una sol·lució alternativa que, al fer el REST request i al rebre'l, canvii els `?` per una cadena de text, com ara `_INTERROGANT_`.

**Comment by BrunoBA91** [comment]
M'animo a fer-ho! Si tinc qualsevol dubte t'ho dic!

**Comment by Masclins** [comment]
Potser aquesta pregunta de StackOverflow t'ajuda: https://stackoverflow.com/questions/45870164/how-to-get-parameter-which-is-containing-question-mark-from-rest-url-in-sprin

**Comment by BrunoBA91** [comment]
Fantàstic el link que has enviat! Sembla ser que és la solució tot i que encara no està implantada. Per a caràcters especials o reservats en URLs caldrà doncs codificar-los. Aquí tenim els codis per futures referències: https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by kenan-rhoton** [comment]
Comentari: la solució típica per al tema dels caràcters extranys en urls es enviar les coses en Base64 🙃
