### ISSUE TITLE
Analitzar dades de cerca

### ISSUE THREAD

**Issue by Atlantidattt** [Masclins/signepedia#60]
Ens falta molt vocabulari, per començar a treballar ja tenim el llistat de vocabulari del nivell A2 de català (`paraules_pendent.txt`).
Però pensant a mig i llarg plaç estaria bé poder analitzar les dades de cerca per saber quines paraules de les que no tenim es busquen més per tal de prioritzar-les en el `paraules_pendent.txt`.

**Comment by Masclins** [comment]
**Molt bona idea!**
Em temo que això implicaria fer servir una Base de Dades, que m'agradaria evitar tant com sigui possible.

Hi ha una alternativa, que és escriure en un .csv les paraules que es cerquin i no tinguem registrades, però provablement hauriem de posar-hi un límit per evitar que es torni enorme (tipus, només les últimes 100 paraules).

**Comment by kenan-rhoton** [comment]
Fan falta 100.000 de 10 caràcters per omplir 1 MB en un fitxer de text. Sobretot si només es registren les no trobades, dubto que hi hagi mai un problema d'espai 🙃
Més encara si primer es cerca al fitxer si la paraula exsteix i senzillament s'incremente un camp "quantitat"

**Comment by Masclins** [comment]
Doncs caldrai veure on guardem això... Si no m'equivoco, ara mateix es guardaria a la màquina virtual creaqda pel Docker, pel que a la que es desmuntés es perdria la informació.
O bé fem que cada cert temps/nº d'entrades envii la informació a signepedia@gmail.com, o bé investiguem com fer que es desi a l'ordinador que està executant el docker...

**Comment by kenan-rhoton** [comment]
Es pot muntar un volum de docker que faci que els arxius hi siguin també a la màquina local
Jo recomanaria un CSV amb tres camps: `paraula`, `número de cerques`, `últim cop que ha sigut cercada`.
I es podria mantenir ordenat segons l'últim accés, per exemple.
També es podria fer en un JSON, però potser és menys pràctic en quant a mirar-lo a simple vista.

**Comment by Masclins** [comment]
M'acabo d'adonar que això és molt similar a #142 (si no el mateix).
Tanco aquesta issue.
