### ISSUE TITLE
Difondre el projecte

### ISSUE THREAD

**Issue by Atlantidattt** [Masclins/signepedia#62]
Actualment hi ha 0 coneixement i visualització del projecte. Això dificulta la col·laboració amb altres persones o entitats. Pel que resulta molt complicada la part d'ampliar vocabulari.
Proposo que quan es puguin penjar vídeos des del frontend i tinguem un servidor es faci difusió a totes les entitats de persones sordes de Catalunya, així com centres que ensenyen la LSC. A més, també proposo crear una conta de Facebook i Twitter per donar més visibilitat al projecte.

**Comment by Masclins** [comment]
Parlant-ho i veient la importància d'aquesta part, crec que més adeqüat que tenir-ho com a issue, lo seu seria crear un nou projecte sobre això, ja que no es tracta d'un problema del codi que calgui solucionar si no una serie d'accions que milloraràn el servei que ofreim.

**Comment by Masclins** [comment]
Tanco aquesta issue ara que ja s'ha creat el Projecte per gestionar-ho.
D'aquesta manera no tenim issues obertes que no haurien de tocar el codi.
