### ISSUE TITLE
Escriure "Avís legal" i "Política de privacitat"

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#81]
Ara que ja es poden pujar vídeos mitjançant el frontend, i abans que l'aplicació sigui pública (i.e. que es pugui accedir remotament), caldrà escriure els documents d'*Avís legal* i *Política de privacitat*.

Tant aviat com tothom pugui pujar vídeos, hem d'estar segurs que són conscients de que el vídeo es penjarà a la web, i hem d'evitar possibles problemes degut a això.

Caldria trobar algú que sigui capaç de redactar aquests documents o buscar una plantilla per internet. Un cop ho tinguem, jo mateix puc fer que apareguin en el formulari i que calgui acceptar-los per enviar el vídeo.

**Comment by Masclins** [comment]
Potser aquestes informacions de la WikiSign poden ajudar: http://lsc.wikisign.org/wiki/Wikisign:CopyrightCat https://creativecommons.org/licenses/by-sa/2.0/es/deed.ca

**Comment by Atlantidattt** [comment]
Crec que si adjuntem la llicència de CreativeCommons actual, ja n'hi haurà prou.
D'altra banda, hauriem de preguntar si la persona qui penja el vídeo n'és l'autor i si és major d'edat (per la llei de protecció al menor).

**Comment by Masclins** [comment]
Doncs serà qüestió de començar a escriure-ho a la branca `Masclins:llicencia`.
De moment, allà, només he afegit una petita notificació a `LICENSE` de que els vídeos tenen llicència Creative Commons (i específicament quina) i un botonet dels que has de marcar a l'hora de pujar vídeos.

**Comment by Masclins** [comment]
Crec que ens poden servir:
https://www.youtube.com/t/terms
https://policies.google.com/privacy?hl=ca
