### ISSUE TITLE
Re-netejar vocabulari

### ISSUE THREAD

**Issue by BrunoBA91** [Masclins/signepedia#84]
He estat mirant el vocabulari i me n'he adonat que hi ha certs errors. Alguns imperceptibles a primera vista com: "ho sento , però et fots" conté un espai de més i dificulta la cerca (l'espai tot just després de "sento ,"). Algun signe "?" que falta al final d'una pregunta com "què et sembla?". 
És per això que obro aquesta issue per a revisar de nou tot aviam què se'ns ha passat per alt.

**Comment by Masclins** [comment]
*ho sento, però et fots* estarà sol·lucionat a la branca `cleanup`.
Hi ha determinats uns símbols especials que no haurien de portar espai abans (al unir la `"paraula"` amb la `"nota"`). Faltava afegir-hi la `','`.

**Comment by Masclins** [comment]
Després de #94 al `diccionari.csv` també s'hi poden fer servir majúscules. Caldria revisar que no m'he deixat cap nom propi sense corregir.

**Comment by Masclins** [comment]
Després de #107 caldria realment fer una revisió. Segurament podem fer una millora de la base de dades amb el nou sistema. Igualment, podrien haver-hi alguns problemes.

**Comment by Atlantidattt** [comment]
Amb el #114 tema majúscules revisat i correcte. Canviar algunes entrades per adaptar-les al nou sistema.
Tema preguntes o partícules interrogatives, resta a l'espera dels vídeos que haig de gravar per completar aquest cap (en falten molts) i aleshores faré la correcció i categorització a fons.
