### ISSUE TITLE
Extreure mail i password del codi

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#88]
Amb #80, vaig introduir el mail i password de la signepedia al codi per tal de que pogués enviar mails.
Ara bé, per seguretat seria millor que aquests paràmetres no hi fóssin presents.

Se m'ocurreix que siguin paràmetres al cridar `node src/main.js` (de l'estil `node src/main.js mail pass`). De totes maneres, però, caldria que al cridar `docker-compose up` també es poguéssin passar aquests dos paràmetres que es farien servir per executar el frontend (i aquesta part ja no sé com fer).

**Comment by kenan-rhoton** [comment]
Això hauria d'estar definit en un fitxer de configuració (que pot ser un JSON) que anés FORA del github (i s'hauria de canviar la contrasenya de l'email, perque ja ha estat compromesa degut a que github és públic).

Alhora, s'hauria de fer que si el fitxer no existeix a la màquina on s'està executant, es deshabilita la funcionalitat dels emails.
