### ISSUE TITLE
Respectar minúscules/majúscules

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#93]
Actualment la paraula que l'usuari cerca la passem a minúscules. Tots els processos que segueixen es fan assumint que totes les paraules estan en minúscules.

Això provoca que els noms propis es mostrin en minúscules, quan són alternatives, o una correcció ortogràfica que no respecta les majúscules que l'usuari ha fet servir.

Seria interessant poder tenir registrades al diccionari paraules en majúscules i mantenir la paraula tal com l'ha escrit l'usuari, però sense que suposi un problema per relacionar `Barcelona` i `barcelona`, per exemple.

Al aplicar aquest canvi, seria interessant, també, actualitzar les paraules del `diccionari.csv` perque els noms propis estiguéssin en majúscula inicial.

**Comment by kenan-rhoton** [comment]
Això hauria de ser solucionable per pur frontend, crec, ja que frontend sap com ho ha escrit l'usuari, pot mantenir les majúscules com son.

**Comment by Masclins** [comment]
La part de dir-li *No tenim "Paraula" registrada.* ja es fa bé.
El problema està amb les correccions (que gestiona el backend i el frontend no sap corregir) o les alternatives, que venen derivades del que hi ha a `diccionari.csv`.

El tema crec que seria simplement no convertir la paraula sinó fer una comparació de la paraula cercada i l'entrada al diccionari ambdues en minúscules, sense canviar cap de les dues. Així podriem tenir majúscules al diccionari i també cercar correccions amb majúscules.
