### ISSUE TITLE
Dissenyar el formulari per la pujada de vídeos

### ISSUE THREAD

**Issue by Masclins** [Masclins/signepedia#98]
Dividint #5:

Ara mateix manté el mateix format que la pàgina principal, que es fa servir per la cerca.
Caldria editar-lo perque sigui més agradable a la vista i aclari quins camps són obligatoris i la seva funció.

**Comment by Mireiatt** [comment]
He trobat aquesta pàgina força engrescadora i atractiva. Parla d'inserir videos. M'agraden molt el to i la simplicitat visual. Potser us donarà idees.

https://blog.ensalza.com/como-insertar-en-tu-pagina-un-video-de-vimeo/

**Comment by Masclins** [comment]
Això és el que fem per incrustar vídeos de youtube.
Aquesta issue tracta de com dissenyem el formulari mitjançant el qual els usuaris envien vídeos.
